### ISSUE TITLE
The LBM algorithm is incorrect

### ISSUE THREAD

**Issue by thisKing** [cornerstonejs/calculate-suv#15]
![image](https://user-images.githubusercontent.com/22740226/164131976-ea7600c6-5ee2-4356-822f-5054c1c20869.png)

M is  -120 
F   is  -148

I use UNITED IMAGE Manufacturer Software（上海联影） tested

**Comment by thisKing** [comment]
When I used UNITED IMAGE to test LBM, I found it was not correct. There was an algorithm reference link in the code, and I found that the male and female 120 and 148 in the code were written in reverse with the reference algorithm, so I changed it.  The final value is the same as the equipment manufacturer UNITED IMAGE

**Comment by salimkanoun** [comment]
So the actual computation is following James PE here a paper confirming the actual value are inverted in the code https://ejnmmiphys.springeropen.com/articles/10.1186/s40658-021-00358-7

**Comment by pwespi** [comment]
Regarding the different SUV LBM types. This is the link to the DICOM standard:
*https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_c.8.9.html

So currently SUV LBM is implemented (using James method), but there is also SUV LBMJANMA which would use Janmahasatian method. Something to look into for the future...
